---
title: "《环境保护与规划》课程网站"
author: "**[田丰](http://jszy.whu.edu.cn/tian_feng/) 武汉大学 遥感信息工程学院**"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
---


欢迎访问！该课程主要面向大二年级第二学期学生，其他年级学生也可选课。

# 网站内容

-   课程教学大纲和教学日历
-   课程实验指导
-   课程相关资源的链接

# 课程背景介绍

武汉大学遥感学院本科生专业选修课"环境保护与规划"一直由万幼川教授主讲，内容分为5大部分，包括：遥感在环境中的应用、环境概论、大气污染及污染扩散模型、水质模型与水质信息系统、植被生态模型，后因课时数下调至32个，万教授删减了植被生态模型部分。2022年开始，在万教授退休之际，我将课程接手过来，正赶上武汉大学进行2023版本科生培养方案修订，在系里讨论时，有位国际著名的定量遥感学家提出：遥感的学生应该学习地球系统科学相关内容，而目前的课表中没有涉及。系里的老师们都非常赞同，我于是准备在课程中增加地球系统科学的一些要点内容。

地球系统科学是近半个世纪以来随着全球变化而发展起来的学科，与卫星遥感技术和计算机复杂系统模拟紧密关联。随着对全球变化的研究，人们意识到地球不同圈层之间紧密关联、相互影响，要搞清楚全球变化的问题，需建立地球是一个整体的认知模式。同时，对地球系统内各大圈层的认知能够促进遥感技术更好应用于各个地学研究领域，开展深入的学科交叉融合，为同学们今后开展研究工作打下良好基础。

在调查国内外地球系统科学课程教学的相关情况之后，发现国内鲜有相关的公开课，更多是地质类的课程，而YouTube上有加州大学-欧文分校（UC Irvine）开设的地球系统科学导论（ESS 1: Introduction to Earth System Science）[公开课](http://www.infocobuild.com/education/audio-video-courses/earth-environment/ESS1-Fall2013-UCI/lecture-01.html)，任课教师为Julie Ferguson教授，教材为《The Blue Planet: An Introduction to Earth System Science》，作者 Brian J. Skinner 和 Barbara W. Murch，教材可以在武大图书馆阅读电子版，有600多页。我发现该公开课及教材的质量都很高，非常有趣，且难度和深度均适宜，我从中也收获颇多，补上了自己在地球系统科学方面的很多知识漏洞。于是决定以将该课程移植到我的课上来，但是Julie Ferguson教授的很多例子都是针对加州和美国的具体情况给出，如果原封不动的照搬过来，对我们的学生来说会由于背景知识不足而产生非常晦涩和奇怪的感觉。另外，通过调查本校本科生教学计划，发现学生在大一的时候学过一门"自然地理学"的课程，对地球系统的大气圈、地圈、水圈、生物圈四大圈层已经有过一些介绍。再通过请教系里的教学主任张熠老师和教学副院长龚龑老师，决定以这门[公开课](http://www.infocobuild.com/education/audio-video-courses/earth-environment/ESS1-Fall2013-UCI/lecture-01.html)和教材为基础，结合自己在植被生态遥感领域的研究，重新设计课程教学内容。

由于是公开课和教材是全英文的，很多专业术语，我们的学生课下自学起来会比较吃力，目前又没有现成的译著，我于是打算从书的目录、节要、主要知识点开始，逐章节进行翻译，积累成一本课程讲义。由于是第一次授课，缺乏经验，不当之处请同学们多多包涵，有意见和建议也请不吝赐教，共同完善"地球系统科学导论"（环境保护与规划）这门课。

再次翻看万幼川教授的课件，发现其第二部分环境概论也很大程度上涉及到了地球系统的四大圈层及环境问题，因此这门课并没有完全脱离之前的内容。

# 说明

课程内容还在持续更新中......
